# Generated by Django 3.0.8 on 2020-07-05 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicentry',
            name='slug',
            field=models.SlugField(default='sluggy', max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
