# Generated by Django 3.0.8 on 2020-07-10 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20200620_2058'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Greeting',
        ),
    ]
