# Generated by Django 3.0.8 on 2020-07-09 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200620_2110'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogentry',
            options={'ordering': ['-pub_date']},
        ),
        migrations.AddField(
            model_name='blogentry',
            name='slug',
            field=models.SlugField(default='floopy', max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blogentry',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=0),
        ),
    ]
