# Generated by Django 3.0.8 on 2020-07-15 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knot', '0003_auto_20200715_0511'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='knotentry',
            options={'ordering': ['-pub_date', 'pk']},
        ),
    ]
