# Generated by Django 3.0.8 on 2020-07-15 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knot', '0004_auto_20200715_0550'),
    ]

    operations = [
        migrations.AddField(
            model_name='knotentry',
            name='page_num',
            field=models.IntegerField(default=0),
        ),
    ]
