# Generated by Django 3.0.8 on 2020-07-15 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knot', '0005_knotentry_page_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knotentry',
            name='page_num',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
