# Generated by Django 3.0.8 on 2020-07-15 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knot', '0006_auto_20200715_1659'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='knotentry',
            options={'ordering': ['-page_num', 'pk']},
        ),
    ]
