# Generated by Django 3.0.8 on 2020-07-15 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knot', '0007_auto_20200715_1701'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='knotentry',
            name='slug',
        ),
    ]
